package org.falcsim.exit;

public enum ExitCodes {

	STATUS_NA(2, "STATUS_NA"),
	
	NOTHING_TO_DO(1, "NOTHING_TO_DO"),
	EXIT_SUCCESS(0, "EXIT_SUCCESS"),
	EXIT_ERROR(-1, "EXIT_ERROR"),
	
	FALC_PROJECT_LOAD_ERROR(-2, "FALC_PROJECT_LOAD_ERROR"),
	FALC_TABLE_LOAD_ERROR(-3, "FALC_TABLE_LOAD_ERROR"),
	
	SYNTHESE_GENERAL(-10, "SYNTHESE_GENERAL"),
	SYNTHESE_DATA_ERROR(-11, "SYNTHESE_DATA_ERROR"),
	SYNTHESE_CALC_MATRIX_NAN(-12, "SYNTHESE_CALC_MATRIX_NAN"),
	SYNTHESE_CALC_DISTANCE_MISSING(-13, "SYNTHESE_CALC_DISTANCE_MISSING"),
	SYNTHESE_ENTROPY_NAN(-14, "SYNTHESE_ENTROPY_NAN"),
	SYNTHESE_POPULATE_ERROR(-15, "SYNTHESE_POPULATE_ERROR"),
	
	AV_GENERAL_ERROR(-30, "AV_GENERAL_ERROR"),

	LOCATION_SUBSET_GENERAL_ERROR(-40, "LOCATION_SUBSET_GENERAL_ERROR"),

	UNIVERSE_GENERAL_ERROR(-50, "UNIVERSE_GENERAL_ERROR"),
	UNIVERSE_COPY_ERROR(-51, "UNIVERSE_COPY_ERROR"),
	
	RANDOM_GENERAL_ERROR(-60, "RANDOM_GENERAL_ERROR"),
	RANDOM_LIST_ERROR(-61, "RANDOM_LIST_ERROR"),
	
	DISTANCES_GENERAL_ERROR(-70, "DISTANCES_GENERAL_ERROR"),
	DISTANCES_CENTROIDS_ERROR(-71, "DISTANCES_CENTROIDS_ERROR"),
	DISTANCES_STREET_MAP_ERROR(-72, "DISTANCES_STREET_MAP_ERROR"),
	DISTANCES_ARE_FILES_ERROR(-73, "DISTANCES_ARE_FILES_ERROR"),
	DISTANCES_NO_CONNECTION_ERROR(-74, "DISTANCES_NO_CONNECTION_ERROR"),
	DISTANCES_RESCALE(-75, "DISTANCES_RESCALE"),
	
	RUN_INDICATORS_GENERAL_ERROR(-80, "RUN_INDICATORS_GENERAL_ERROR"),
	RUN_INDICATORS_LOADING_ERROR(-81, "RUN_INDICATORS_LOADING_ERROR"),
	RUN_INDICATORS_EXPORTING_ERROR(-82, "RUN_INDICATORS_EXPORTING_ERROR"),
	
	MODELS_PREFIX_GENERAL_ERROR(-90, "MODELS_PREFIX_GENERAL_ERROR"),
	MODELS_BUSINESS_ERROR(-91, "MODELS_BUSINESS_ERROR"),
	MODELS_HH_FORMATION_ERROR(-92, "MODELS_HH_FORMATION_ERROR"),
	MODELS_LD_METHODS_ERROR(-93, "MODELS_LD_METHODS_ERROR"),
	MODELS_MIGRATION_ERROR(-94, "MODELS_MIGRATION_ERROR"),
	MODELS_IMMIGRATION_ERROR(-95, "MODELS_IMMIGRATION_ERROR"),
	MODELS_HH_RELOCATION_ERROR(-96, "MODELS_HH_RELOCATION_ERROR"),
	MODELS_BB_RELOCATION_ERROR(-97, "MODELS_BB_RELOCATION_ERROR"),
	MODELS_LAND_USAGE_ERROR(-98, "MODELS_LAND_USAGE_ERROR"),
	MODELS_MOVING_ERROR(-99, "MODELS_MOVING_ERROR"),
	
	TIME_MONITOR_GENERAL_ERROR(-100, "TIME_MONITOR_GENERAL_ERROR"),
	SCENARIOS_GENERAL_ERROR(-200, "SCENARIOS_GENERAL_ERROR"),
	STATISTICS_PREFIX(-300, "STATISTICS_PREFIX"),
	
	THREAD_ERROR(-1000, "THREAD_ERROR"),
	MEMORY_ERROR(-2000, "MEMORY_ERROR"),
	
	SYNTHESE_MODULE_MODIFIED(-4011, "SYNTHESE_MODULE_MODIFIED"), 
	SYNTHESE_MODULE_EXPIRED(-4012, "SYNTHESE_MODULE_EXPIRED"),
	SYNTHESE_MODULE_INVALID(-4013, "SYNTHESE_MODULE_INVALID"),
	SYNTHESE_MODULE_NOT_PRESENT(-4014, "SYNTHESE_MODULE_NOT_PRESENT"),
	
	DISTANCES_MODULE_MODIFIED(-4071, "DISTANCES_MODULE_MODIFIED"), 
	DISTANCES_MODULE_EXPIRED(-4072, "DISTANCES_MODULE_EXPIRED"),
	DISTANCES_MODULE_INVALID(-4073, "DISTANCES_MODULE_INVALID"),
	DISTANCES_MODULE_NOT_PRESENT(-4074, "DISTANCES_MODULE_NOT_PRESENT"),	
	
	STATISTICS_MODULE_MODIFIED(-4301, "STATISTICS_MODULE_MODIFIED"), 
	STATISTICS_MODULE_EXPIRED(-4302, "STATISTICS_MODULE_EXPIRED"),
	STATISTICS_MODULE_INVALID(-4303, "STATISTICS_MODULE_INVALID"),
	STATISTICS_MODULE_NOT_PRESENT(-4304, "STATISTICS_MODULE_NOT_PRESENT"),
	
	UI_LOAD_ERROR(-4501, "UI_LOAD_ERROR"),
	UI_INIT_ERROR(-4502, "UI_INIT_ERROR"),
	UI_CORE_NOT_FOUND(-4503, "UI_CORE_NOT_FOUND");
	
	private final int id;
	private final String message;
	
	ExitCodes(int id, String message){
		this.id = id;
		this.message = message;
	}
	
	public int getValue(){
		return id;
	}
	
	public String getMessage(){
		return message;
	}
	
	public static ExitCodes forCode(int id){
		for(ExitCodes ec : ExitCodes.values()){
			if(ec.id == id)
				return ec;
		}
		return STATUS_NA;
	}
}
